version: '3'
services:
  bungeecord:
    build: bungeecord/
    ports:
      - "25565:25565"
    links:
      - spigot:spigot
    stdin_open: true
    tty: true
  spigot:
    build: spigot
    ports:
      - "25566:25566"
    stdin_open: true
    tty: true
